version: '3.5'

services:
  db:
    image: postgres:14.2
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db

  accrual:
    build:
      context: ./
      dockerfile: ./build/accrual.dockerfile
    ports:
      - '8081:8080'

  gophermart:
    build:
      context: ./
      dockerfile: ./build/gophermart.dockerfile
    environment:
      - RUN_ADDRESS=127.0.0.1:8080
      - DATABASE_URI="user=username password=password dbname=db sslmode=disable"
      - ACCRUAL_SYSTEM_ADDRESS=http://accrual:8080
    ports:
      - '8080:8080'
